### ISSUE TITLE
create actions for rclone

### ISSUE THREAD

**Issue by torwag** [Evidlo/remarkable_pdflets#1]
Hi,

I used rclone to sync my rM with my nextcloud for some time. However, as there was no GUI, I relied on a systemd-timer which called rclone every X minutes and there was almost no feedback on whether it worked out or not. 
If I understand your concept right, one could create a document, that after open and closing it, would trigger a rclone-based sync on demand and writes the result of that sync into the file, thus, the user can get some feedback.
Sounds maybe strange, but it would be an elegant way to enhance rM without messing with the original xochitl software.

**Comment by Evidlo** [comment]
Should be trivial to implement.  If you want to do this I'd be happy to merge.

All you need to do is replace the top part of `weather.sh` or `twitter.sh` with `out=$(rclone_command 2>&1)`.

I'll add information on how this stuff works to the readme.

**Comment by Evidlo** [comment]
I added `template/` which should make it much clearer how to write a pdflet.

**Comment by torwag** [comment]
Thanks I will look into it and try to get rclone working with it
