### ISSUE TITLE
More details of the codes.

### ISSUE THREAD

**Issue by boangs** [Evidlo/remarkable_pdflets#3]
I tried many times ,every time I got a blank page.

out=$(echo hello world 2>&1)

This display nothing.

Can you help me ?

**Comment by Evidlo** [comment]
Try the latest commit.

**Comment by Evidlo** [comment]
Did you at least get the "Updated ..." message at the bottom?

**Comment by boangs** [comment]
No. It's  still a blank page. 
I download the pdf file from remarkable with a ftp client. I can see "Hello world" and the "Update " message. But on remarkable , it's not a pdf file, it's a blank notebook that I can add new pages.

The "weather " app works fine on my remarkable  but the "template " app.

**Comment by Evidlo** [comment]
Try deleting `/home/root/.local/share/remarkable/xochitl/[UUID].cache/0.png` and then manually run the script.  It should regenerate `0.png`.

**Comment by boangs** [comment]
Ok, It's worked. Thank you
