### ISSUE TITLE
xochitl can't open PDFs generated by script

### ISSUE THREAD

**Issue by vdrummer** [Evidlo/remarkable_pdflets#4]
I'm using 1.7.2.3 with the draft launcher.
I tried both a hello world pdfflet and the weather pdflet. In both cases, the generated PDF is readable on my PC but not on the rM. 
For hello world, it's just a blank page with a blank OTHER_UUID.png in the cache folder.
For weather, there is no png there at all and I get an error on the rM saying the document couldn't be opened.

Any ideas what might have gone wrong?

Edit:
The weather PDF is now working. I'll try to work it from there.

**Comment by Evidlo** [comment]
This should be fixed now.  The scripts used to delete `0.png`, but with the 1.7 update xochitl gave the pngs a UUID.

**Comment by Evidlo** [comment]
Is this working?
