### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by PepikVaio** [Evidlo/remarkable_pdflets#6]
Hi, is this stil working on 3.x?
Thank you.

**Comment by Evidlo** [comment]
Sorry for the slow response.  I'm not sure if this still works.  If you tried it, let me know.

**Comment by PepikVaio** [comment]
I copied the entire "remarkable_pdflets-master" folder to remarkable "home/root".

Ran install.sh and got this error:

-sh: ./install.sh: Permission denied

Am I doing it right?

**Comment by PepikVaio** [comment]
OK, I forgot chmod + x.

Now I get the error:
/usr/bin/dbclient: Connection to root@10.11.99.1:22 exited: Connect failed: Connection timed out
lost connection

**Comment by Evidlo** [comment]
You're supposed to run `install.sh` from your host computer, not the device.

**Comment by PepikVaio** [comment]
OK, so I don't understand how to install. Can you please provide step by step how to try?

So should I copy something to remarkable?
Or should I have everything on the PC?

Thank you

**Comment by Evidlo** [comment]
You just clone the repo to your host machine with the reMarkable connected, `chmod +x` the install script, then execute the script.  It will automatically copy everything needed to the reMarkable and restart it.

This is for Linux/OSX.  If on Windows, you'd need to install WSL or use Cygwin to run the bash script, or just do what the installer does by hand.

**Comment by PepikVaio** [comment]
OK - great.
I had to modify the script to access via wifi instead of cable.

The PDF has been uploaded - and is working.
Where can I adjust the time zone?
Where can I edit the design?
I would like to add a margin because the output touches the edge of the screen.
Where can I add more days?

Thank you.

**Comment by PepikVaio** [comment]
OK, I figured out some settings, what and how.
I just don't know how to use wget with diacritics for special characters (řťýúíóšďžčň).

Don't you know?

**Comment by Evidlo** [comment]
You can try piping the output of wget into `iconv` and replace them that way.

https://stackoverflow.com/questions/10207354/how-to-remove-all-of-the-diacritics-from-a-file

> I would like to add a margin because the output touches the edge of the screen.

You can play with [these lines](https://github.com/Evidlo/remarkable_pdflets/blob/master/weather/weather.sh#L67-L68) to shrink/move the text on the page.  The link at the top of the script explains what those commands do.

**Comment by PepikVaio** [comment]
Thanks this problem is solved.
I will try playing woth this.
